settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: digitalniplan-hr
    name: digitalniplan.hr
    url: 'https://www.digitalniplan.hr/'
    linkable: false

  - id: aviteh-hr
    name: aviteh.hr
    url: 'https://www.aviteh.hr/'
    linkable: false

  - id: aviteh-ba
    name: aviteh.ba
    url: 'https://www.aviteh.ba/'
    linkable: false

  - id: beautypharmacy-hr
    name: beautypharmacy.hr
    url: 'https://www.beautypharmacy.hr/'
    linkable: false

  - id: bebastore-hr
    name: bebastore.hr
    url: 'https://www.bebastore.hr/'
    linkable: false

  - id: eljekarna-hr
    name: eljekarna.hr
    url: 'https://www.eljekarna.hr/'
    linkable: false
    
  - id: igrackedenis-hr
    name: igrackedenis.hr
    url: 'https://igrackedenis.hr/'
    linkable: false
    
  - id: igrackedenis-ba
    name: igrackedenis.ba
    url: 'https://igrackedenis.ba/'
    linkable: false

  - id: shopland-hr
    name: shopland.hr
    url: 'https://www.shopland.hr/'
    linkable: false

  - id: lackovic-hr
    name: lackovic.hr
    url: 'https://www.lackovic.hr/'
    linkable: false

  - id: ljekarna-fett-hr
    name: ljekarna-fett.hr
    url: 'https://www.ljekarna-fett.hr/'
    linkable: false

  - id: pharmashop-hr
    name: pharmashop.hr
    url: 'https://www.pharmashop.hr/'
    linkable: false

  - id: repromaterijali-com
    name: repromaterijali.com
    url: 'https://repromaterijali.com/'
    linkable: false

  - id: socap-hr
    name: socap.hr
    url: 'https://www.socap.hr/'
    linkable: false